### ISSUE TITLE
Role Based Menu

### ISSUE THREAD

**Issue by papyr** [mo-esmp/DynamicRoleBasedAuthorizationNETCore#15]
Hello, can we generate a Role Based Menu option when we configure services.

Also I think we can use this in our template for [breacrumbs ](https://github.com/zHaytam/SmartBreadcrumbs) 
This template is much more easier to use than the dotnet boxed or rehans template. 

Do you have any suggestions to customizing T4 tempaltes to do scaffolding from table controller and views

thanks

**Comment by mo-esmp** [comment]
Right now it could be done via `secure-content` tag helper to generate role-based menu:
```
<secure-content asp-area="" asp-controller="Role" asp-action="Index">
    <li><a asp-area="" asp-controller="Role" asp-action="Index">Role</a></li>
</secure-content>
```
As you said it's a good idea to implement functionality like `breacrumbs` for generating a role-based menu. I'm not good at using T4 templates and honestly have no idea about how to do scaffolding from table controller and views.
