### ISSUE TITLE
[Question]RoleStore.json move to DB

### ISSUE THREAD

**Issue by danijel88** [mo-esmp/DynamicRoleBasedAuthorizationNETCore#18]
Where I can find RoleStore.json ?
Is it possible to save permissions in db ?

**Comment by mo-esmp** [comment]
The default path to save `RoleStore.json` is the location of the application's DLLs, for example in debug mode, the location is `bin\Debug` folder. You can also change the default location `.AddJsonStore(options => options.FilePath = "FilePath");`

Within tomorrow I will publish a new nuget package to save role access to the SQL Server database.

**Comment by mo-esmp** [comment]
To save role access in the database, install [DynamicAuthorization.Mvc.MsSqlServerStore](https://www.nuget.org/packages/DynamicAuthorization.Mvc.MsSqlServerStore) store.
