### ISSUE TITLE
accessList is always returning null

### ISSUE THREAD

**Issue by tgerevini** [mo-esmp/DynamicRoleBasedAuthorizationNETCore#21]
Hi, been stuck in this problem and i can't figure it out why i'm getting the accessList null... I can create and edit the role, but no items in accesslist.

Here's my startup:
```

  services.AddDbContext<LoginContext>(options =>
            {
                options.UseSqlServer(Configuration.GetConnectionString("Default"));
            });
            services.AddIdentity<User, IdentityRole>(options =>
            {
                options.Password.RequiredLength = 3;
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireUppercase = false;
                options.Password.RequireLowercase = false;
                options.Password.RequireDigit = false;
                options.User.RequireUniqueEmail = true;
            }).AddEntityFrameworkStores<LoginContext>()
              .AddErrorDescriber<TranslatedIdentityErrorDescriber>();

            services
                .AddDynamicAuthorization<LoginContext>(options => options.DefaultAdminUser = "admin")
                .AddSqlServerStore(options => options.ConnectionString = "Default"); 

            services.ConfigureApplicationCookie(options =>
            {
                options.LoginPath = "/Login";
            });

            services.AddScoped<IUserClaimsPrincipalFactory<User>, CustomUserClaimsPrincipalFactory>();

```

Here's my DbContext class, i think it might be here the problem, but i don't know what else to try:

```
   public class LoginContext : IdentityDbContext
    {
        public LoginContext(DbContextOptions<LoginContext> options) : base(options)
        {
            //irá criar o banco e a estrutura de tabelas necessárias
            this.Database.EnsureCreated();
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            builder.ApplyConfiguration<User>(new UserConfiguration());
            builder.ApplyConfiguration<Role>(new RoleConfiguration());
        }
    }   
    public class RoleConfiguration : IEntityTypeConfiguration<Role>
    {
        public void Configure(EntityTypeBuilder<Role> builder)
        {
       
        }
    }
```

When debbuging, both lines seens successfull, the objects are loaded correctly:

```
await _roleAccessStore.AddRoleAccessAsync(roleAccess);
 await _roleAccessStore.EditRoleAccessAsync(roleAccess);
```

Here, the return is always null:

` var accessList = await _roleAccessStore.GetRoleAccessAsync(role.Id);`

Any idea what could be wrong here please? Thanks

**Comment by mo-esmp** [comment]
Hi @tgerevini 
What store type do you use? `JSON` or `SQLServer`? 
If `roleAccess` object is not `null` then after calling `await _roleAccessStore.AddRoleAccessAsync(roleAccess);`, it should be stored, check the store to see  values are saved or not.
It would be a great help if you provide a project on Github or send me by email that demonstrates the issue.

**Comment by tgerevini** [comment]
I'm using SQLServer. I got you an access to the project on github, i really apreciate your help!
https://github.com/solutions-atv/FrameworkBase

i'm going to look into the roleAccess object and see it i's storing the value, if i still dont manage to make it work, i'll keep you updated, thanks a lot! The default user and pwd is admin, cheers!

ps.: I changed the startup to use  .AddJsonStore() and it worked, but i need to be saved on the database.

I also noticed that the DynamicAuthorizationOptions class doesn't seen to be updated:

```
#region Assembly DynamicAuthorization.Mvc.Core, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null
// C:\Users\gerev\.nuget\packages\dynamicauthorization.mvc.core\1.1.1\lib\net5.0\DynamicAuthorization.Mvc.Core.dll
#endregion

namespace DynamicAuthorization.Mvc.Core.Models
{
    public class DynamicAuthorizationOptions
    {
        public DynamicAuthorizationOptions();

        public string DefaultAdminUser { get; set; }
    }
}

```
I noticed when i tried to implement the User Role functionality today

**Comment by mo-esmp** [comment]
I will check the project soon and I will update you.

**Comment by mo-esmp** [comment]
I have debugged your project and everything worked as expected and I couldn't re-produce malfunctionality you mentioned.

![d2](https://user-images.githubusercontent.com/1659032/112191714-eb0a5900-8c23-11eb-9fac-8d8582858692.jpg)
![d1](https://user-images.githubusercontent.com/1659032/112191748-f3629400-8c23-11eb-998a-190c9fbb9d1b.jpg)

**Comment by tgerevini** [comment]
I noticed i dont have this table in my database... did you create RoleAccess table?

**Comment by mo-esmp** [comment]
This table will be created automatically when the project has started

**Comment by tgerevini** [comment]
Hmm that's probabily the problem, it's not being created in my environment, only the other ones

![image](https://user-images.githubusercontent.com/34342917/112209768-9a313b00-8bf8-11eb-94a5-0c54455ebca9.png)

**Comment by mo-esmp** [comment]
Run the application with `dotnet run` and check out the logs on console output to see if any error occurs during table creation.

**Comment by tgerevini** [comment]
![image](https://user-images.githubusercontent.com/34342917/112225698-f0f44000-8c0b-11eb-998d-bfc77a6f0b62.png)

: \ 2 - Sources \ git \ solutions-atv \ FrameworkBase \ Directory.Build.targets (70,5): error MSB4801: task factory "CodeTaskFactory" is not supported in the .NET Core version of MSBuild. [D: \ 2 - Sources \ git \ solutions-atv \ FrameworkBase \ FrameworkBase.Domain \ FrameworkBase.Domain.csproj]
D: \ 2 - Sources \ git \ solutions-atv \ FrameworkBase \ Directory.Build.targets (70,5): error MSB4175: Task factory "CodeTaskFactory" was not loaded from assembly "C: \ Program Files \ dotnet \ sdk \ 5.0.201 \ Microsoft.Build.Tasks.Core.dll ". A task factory must return a value for a "TaskType" property. [D: \ 2 - Sources \ git \ solutions-atv \ FrameworkBase \ FrameworkBase.Domain \ FrameworkBase.Domain.csproj]


maybe that's cause i'm using .net core 5.0?

**Comment by mo-esmp** [comment]
No, it's not related to `.NET Core 5.0` because I successfully created a role and access-list with your project. Run the project with VS and instead of `IIS Express` choose `FrameworkBase.UI`

![Screenshot 2021-03-24 031214](https://user-images.githubusercontent.com/1659032/112228371-d55e5900-8c4e-11eb-9611-1cf0d48e9ee0.jpg)

Inside the console, If any errors related to table creation occur, there should be an error message that starts with:

![Screenshot 2021-03-24 031152](https://user-images.githubusercontent.com/1659032/112228735-62a1ad80-8c4f-11eb-9989-bc7e0cbb0bad.jpg)

**Comment by tgerevini** [comment]
ohh i got it now, thanks!
![image](https://user-images.githubusercontent.com/34342917/112229098-19cb0400-8c11-11eb-9b10-91eb48b3a5fa.png)

Now i have a clue on the problem, gonna search for a solution

**Comment by mo-esmp** [comment]
There is a problem with your connection string, check if there is any problem with your connection string.

https://stackoverflow.com/q/8243008/1385614
https://stackoverflow.com/q/30550679/1385614

**Comment by tgerevini** [comment]
Weird, cause the rest of the tables were created.... 
But i got it working! These are the steps that i followed:

1) Changed connection string authentication - from Trusted Connection to Standard Security.
2) Restarting MSSQLSERVER process

It still gave me collation error, but it created the table.

![image](https://user-images.githubusercontent.com/34342917/112233997-4899a800-8c1a-11eb-97fb-b33abe686641.png)

**Comment by tgerevini** [comment]
Now i'm facing problems trying to configure UserRole controller without using the UI. Do you have any walkthrough?

I think i need to set this on statup right?
![image](https://user-images.githubusercontent.com/34342917/112235589-babfbc00-8c1d-11eb-97d3-e9959eb24698.png)

But this **"DynamicAuthorization"** class got no such properties and i'm using the latest version:

![image](https://user-images.githubusercontent.com/34342917/112235906-518c7880-8c1e-11eb-9231-78d25055c925.png)

**Comment by mo-esmp** [comment]
Check the manual branch for a walkthrough:
https://github.com/mo-esmp/DynamicRoleBasedAuthorizationNETCore/tree/manual

> Now i'm facing problems trying to configure UserRole controller without using the UI. Do you have any walkthrough?
> 
> I think i need to set this on statup right?
> ![image](https://user-images.githubusercontent.com/34342917/112235589-babfbc00-8c1d-11eb-97d3-e9959eb24698.png)
>
No, you don't need this. just take a look at the UI project to see how to implement it.
Also in the blow sample, I implemented UI functionallity without using `UI` package:
https://github.com/mo-esmp/DynamicRoleBasedAuthorizationNETCore/tree/master/samples/netcore3.x/SampleMvcWebApp

**Comment by tgerevini** [comment]
Thanks! It's almost working lol... now users / roles and access list is working... The problem i'm facing now is that i added the tagHelper but the application completely ignores this class.

![image](https://user-images.githubusercontent.com/34342917/112570545-fd6fc880-8dc4-11eb-957c-f782d1a66599.png)

I added the secure-content tags as told, but the menu links are always visible no matter what access i add or remove to role. 

![image](https://user-images.githubusercontent.com/34342917/112570839-90a8fe00-8dc5-11eb-9e86-e7bde4760c37.png)

**Comment by mo-esmp** [comment]
I guess you forgot to import your project namespace into the `_ViewImports.cshtml` file
https://github.com/mo-esmp/DynamicRoleBasedAuthorizationNETCore/blob/master/samples/net5/SampleMvcWebWithUi/Views/_ViewImports.cshtml

**Comment by tgerevini** [comment]
Perfect! damn i tried to import on shared view lol, thanks!

Now, is it possible to change the access denied view?

![image](https://user-images.githubusercontent.com/34342917/112727247-74f64280-8f00-11eb-99e3-01e130ac3786.png)

**Comment by mo-esmp** [comment]
I just return [ForbidResult](https://github.com/mo-esmp/DynamicRoleBasedAuthorizationNETCore/blob/16cf6f656f0aaa63021a7adb0b7f0c39852d3947/src/DynamicAuthorization.Mvc.Core/Filters/DynamicAuthorizationFilter.cs#L112) when a user does not have access to a resource. You should handle the error `403` within your application.

This link might help you
https://stackoverflow.com/a/52625797/1385614

**Comment by tgerevini** [comment]
Thanks! Now it's working perfectly!
