### ISSUE TITLE
پیاده سازی کلاس MySecureContentTagHelper در حالت کلاس کاستوم

### ISSUE THREAD

**Issue by mohammadhosseinzavvar** [mo-esmp/DynamicRoleBasedAuthorizationNETCore#24]
سلام
من همه کلاس های identityt و مطابق داکیومنت مایکروسافت سفارشی کردم
ApplicationRole
ApplicationRoleClaim
ApplicationUser
ApplicationUserClaim
ApplicationUserLogin
ApplicationUserRole
ApplicationUserToken
در پیاده سازی کلاس تگ هلپر مطابق زیر خطا داره
`[HtmlTargetElement("secure-content")]
    public class MySecureContentTagHelper : SecureContentTagHelper<ApplicationDbContext, ApplicationUser, ApplicationRole, int>
    {
        public MySecureContentTagHelper(
            ApplicationDbContext dbContext,
            DynamicAuthorizationOptions authorizationOptions,
            IRoleAccessStore roleAccessStore) : base(dbContext, authorizationOptions, roleAccessStore)
        {
        }
    }`

**Comment by mo-esmp** [comment]
:چی خطایی داره؟ تو این سمپل من از اورلود ٨ پارامتر استفاده کردم و خطایی نداره، اون رو چک کنید

https://github.com/mo-esmp/DynamicRoleBasedAuthorizationNETCore/blob/master/samples/net5/SampleMvcWebWithUi/TagHelpers/MySecureContentTagHelper.cs

**Comment by mohammadhosseinzavvar** [comment]
مشکلم حل شد
سپاس
