### ISSUE TITLE
Question: DynamicAuthorization.Mvc.Ui

### ISSUE THREAD

**Issue by ghost** [mo-esmp/DynamicRoleBasedAuthorizationNETCore#26]
Is it possible to scaffold the views of the DynamicAuthorization.Mvc.Ui? I have a theme I am applying to the application, and I want the roles pages to be similarly templated.

Thank you

**Comment by mo-esmp** [comment]
Unfortunately, you can't. The easiest way right now is that copy the `DynamicAuthorization.Mvc.Ui` project into your own project and change it in the way want.

**Comment by ghost** [comment]
Okay thank you. I will do just that. Prior to now I have been implementing it manually. I will continue to do that. And thank you so very much for this awesome project. Been saving my life 3 years now and counting!
