### ISSUE TITLE
Will it merge `DynamicAuthorization.Mvc.MsSqlServerStore` to like `DynamicAuthorization.Mvc.EFStore`

### ISSUE THREAD

**Issue by Cricle** [mo-esmp/DynamicRoleBasedAuthorizationNETCore#34]
Can it export a model given user write in DbContext like DbSet<xxx>, and use DbContext to access data.

This will probably be `Migrations`, `Custom`, `Controlable`, `Scalable`.

**Comment by Cricle** [comment]
Like given interface 

```csharp
public interface IDynamicRoleProvider
{
     DbSet<DynamicRole> DynamicRoles{get;}
}
```

And inject in service to use.

**Comment by mo-esmp** [comment]
It is possible, by adding `DbSet<RoleAccess>` manually or by inheriting `DynamicAuthDbContenct` that has the DbSet (maybe with some more extra helpers).

**Comment by Cricle** [comment]
Thanks. I like this project very much!
