### ISSUE TITLE
hello,i'm having two issues ,first AspNetRoles Access column is always null ,second i have ArgumentNullException in Editing role . Thank you very much

### ISSUE THREAD

**Issue by rust4m** [mo-esmp/DynamicRoleBasedAuthorizationNETCore#5]
``

**Comment by mo-esmp** [comment]
Hi @rustam013, have you pulled latest commit ?

**Comment by rust4m** [comment]
Hi ,latest commit was 8 days ago ,I've downloaded 2 days ago ,is there something i'm doing wrong?thank you

**Comment by rust4m** [comment]
sorry ,you were right ,sorry again ,thanks for reply
