### ISSUE TITLE
How to include Razor Pages & Page Handlers

### ISSUE THREAD

**Issue by tb-mtg** [mo-esmp/DynamicRoleBasedAuthorizationNETCore#6]
Excellent project!

How would I go about handling RazorPages as well as/instead of controllers?

Particularly how to implement MvcControllerDiscovery for Razor Pages & Page Handlers where 
* MvcRazorPageInfo would be equivalent of MvcControllerInfo
* MvcRazorPageHandlerInfo would be equivalent of MvcActionInfo

**Comment by mo-esmp** [comment]
@tb-mtg sorry for answering late. Read this article about [Discovering controller actions and Razor Pages in ASP.NET MVC Core](https://joonasw.net/view/discovering-actions-and-razor-pages).
