### ISSUE TITLE
IMvcControllerDiscovery in .net core2.1

### ISSUE THREAD

**Issue by assadnazar** [mo-esmp/DynamicRoleBasedAuthorizationNETCore#7]
I cant resolve IMvcControllerDiscovery in .net core 2.1... can you guide me with that?

**Comment by mo-esmp** [comment]
What exception do you get ? It would be great if you provide more information.

**Comment by assadnazar** [comment]
I am not getting any reference to the library. Can you tell me library reference to include

**Comment by coskuncinar** [comment]
Change the contents of the file. Also you will be upgraded to the 2.2.

`<Project Sdk="Microsoft.NET.Sdk.Web">`
`  <PropertyGroup>`
`    <TargetFramework>netcoreapp2.2</TargetFramework>`
`    <UserSecretsId>aspnet-DynamicRoleBasedAuthorization-5CB62301-D158-460A-94F8-2B16F86DD954</UserSecretsId>`
`  </PropertyGroup>`
`  <ItemGroup>`
`    <PackageReference Include="Microsoft.AspNetCore.App" />`
`    <PackageReference Include="Microsoft.AspNetCore.All" />`
`    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.2.3" PrivateAssets="All" /> 
`  </ItemGroup> 
`</Project>`

**Comment by coskuncinar** [comment]
Change the contents of the "DynamicRoleBasedAuthorization.csproj". Also you will be upgraded to the 2.2

`<Project Sdk="Microsoft.NET.Sdk.Web">`
`  <PropertyGroup>`
`    <TargetFramework>netcoreapp2.2</TargetFramework>`
`    <UserSecretsId>aspnet-DynamicRoleBasedAuthorization-5CB62301-D158-460A-94F8-2B16F86DD954</UserSecretsId>`
`  </PropertyGroup>`
`  <ItemGroup>`
`    <PackageReference Include="Microsoft.AspNetCore.App" />`
`    <PackageReference Include="Microsoft.AspNetCore.All" />`
`    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.2.3" PrivateAssets="All" /> 
`  </ItemGroup> 
`</Project>`
