### ISSUE TITLE
Cant Get Requested Url in .Net Core 3.1

### ISSUE THREAD

**Issue by MahdiElahi** [mo-esmp/DynamicRoleBasedAuthorizationNETCore#8]
hello please update DynamicRoleBasedAuthorizationNETCore project to .net core 3.1
thanks, a lot 
when i call authorize controller for example /roles/index 
in filter the url is /account/login not show my main path.

because we use app.authorizaiton & serivce.useControllersAndView & app.EndPoint in .net Core 3.1

**Comment by mo-esmp** [comment]
New sample project for .NET Core 3.1 added. Please check the [sample](https://github.com/mo-esmp/DynamicRoleBasedAuthorizationNETCore/tree/master/samples/netcore3.0/DynamicRoleBasedAuthorization) and let me know if you have any issue.
